# Generated by Django 3.1.1 on 2020-10-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peddal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(default='default.jpg', null=True, upload_to='customer_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=800)),
                ('selling_rate', models.IntegerField(default=0, null=True)),
                ('hire_rate', models.IntegerField(default=0, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='cycle_photo')),
                ('rental_status', models.BooleanField(choices=[('False', 'False'), ('True', 'True')], default=True, null=True)),
                ('sold_status', models.BooleanField(choices=[('False', 'False'), ('True', 'True')], default=False, null=True)),
                ('condition', models.CharField(choices=[('Used', 'Used'), ('Brand New', 'Brand New')], max_length=30, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='peddal.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CycleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='cycle_photo')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peddal.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('rental_time', models.TimeField(null=True)),
                ('return_date', models.DateField()),
                ('rental_status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='peddal.customer')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='peddal.cycle')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
