# Generated by Django 3.1.1 on 2020-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peddal', '0002_auto_20201002_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='rental_status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='sold_status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False, null=True),
        ),
    ]
