# Generated by Django 3.1.1 on 2020-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peddal', '0003_auto_20201002_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('Brand New', 'Brand New')], max_length=30, null=True),
        ),
    ]
