# Generated by Django 3.1.1 on 2020-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peddal', '0004_auto_20201002_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='rental_status',
            field=models.BooleanField(choices=[('False', 'False'), ('True', 'True')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='sold_status',
            field=models.BooleanField(choices=[('False', 'False'), ('True', 'True')], default=False, null=True),
        ),
    ]
