# Generated by Django 3.1.1 on 2020-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peddal', '0005_auto_20201002_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='description',
        ),
        migrations.AddField(
            model_name='cycle',
            name='cycle_description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='hire_description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='rental_status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='sold_status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False, null=True),
        ),
    ]
