# Generated by Django 3.1.1 on 2020-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peddal', '0007_auto_20201002_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('Brand New', 'Brand New')], max_length=30, null=True),
        ),
    ]
